# Generated by Django 4.2.30 on 2026-05-04 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('femenil_a', 'Primera Femenil'), ('femenil_b', 'Segunda Femenil'), ('femenil_c', 'Femenil Libre'), ('sub10', 'Sub-10 Infantil'), ('sub13', 'Sub-13 Pre-Juvenil'), ('sub17', 'Sub-17 Juvenil'), ('varonil_a', 'Primera Varonil'), ('varonil_b', 'Segunda Varonil'), ('veteranos', 'Veteranos +35')], max_length=20)),
                ('division', models.CharField(choices=[('femenil', 'Femenil Libre'), ('juvenil', 'Juvenil'), ('varonil', 'Varonil Libre')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/logos/')),
                ('color_principal', models.CharField(default='#0d2137', max_length=7)),
                ('color_secundario', models.CharField(default='#4db8e8', max_length=7)),
                ('horario_entreno', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['division', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('categoria_interes', models.CharField(max_length=20)),
                ('nombre_tutor', models.CharField(max_length=150)),
                ('telefono_tutor', models.CharField(max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(choices=[('director', 'Director General'), ('tecnico', 'Director Técnico'), ('secretaria', 'Secretaria General'), ('arbitro', 'Coordinador de Árbitros'), ('cancha', 'Encargado de Cancha'), ('tesorera', 'Tesorera'), ('otro', 'Otro')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('bio', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.PositiveSmallIntegerField()),
                ('goles_local', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('jugado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('arbitro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_arbitrados', to='guerreros_cf.staff')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='guerreros_cf.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='guerreros_cf.equipo')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('categoria', models.CharField(choices=[('torneo', 'Torneo'), ('resultado', 'Resultados'), ('inscripciones', 'Inscripciones'), ('academia', 'Academia'), ('femenil', 'Femenil'), ('infraestructura', 'Infraestructura'), ('general', 'General')], default='general', max_length=20)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_entrenados', to='guerreros_cf.staff'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('numero_dorsal', models.PositiveSmallIntegerField()),
                ('posicion', models.CharField(choices=[('portero', 'Portero'), ('defensa', 'Defensa'), ('medio', 'Mediocampista'), ('delantero', 'Delantero')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveSmallIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='guerreros_cf.equipo')),
            ],
            options={
                'ordering': ['equipo', 'numero_dorsal'],
                'unique_together': {('equipo', 'numero_dorsal')},
            },
        ),
    ]
