# Generated by Django 4.2.30 on 2026-05-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guerreros_cf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='division',
            field=models.CharField(choices=[('femenil', 'Femenil'), ('juvenil', 'Juvenil'), ('varonil', 'Varonil')], max_length=20),
        ),
        migrations.CreateModel(
            name='NoticiaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='guerreros_cf.noticia')),
            ],
        ),
    ]
