# Generated by Django 4.2.30 on 2026-05-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guerreros_cf', '0002_alter_equipo_division_noticiaimagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['division', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='entrenador',
        ),
    ]
