# Generated by Django 6.0.6 on 2026-06-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerreros_cf', '0009_equipo_logro_quitar_entrenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staffimagen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trofeo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
